# Generated by Django 6.0.4 on 2026-04-19 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spoiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido del Spoiler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spoilers', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Spoiler',
                'verbose_name_plural': 'Spoilers',
                'ordering': ('-created_at',),
            },
        ),
    ]
