# Generated by Django 6.0.4 on 2026-04-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
