# Generated by Django 6.0.4 on 2026-04-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_genre_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spoiler',
        ),
    ]
