# Generated by Django 5.2.12 on 2026-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_country_movie_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Plataforma')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL del Logo')),
            ],
            options={
                'verbose_name': 'Plataforma de Streaming',
                'verbose_name_plural': 'Plataformas de Streaming',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.streamingplatform', verbose_name='Plataformas de Streaming'),
        ),
    ]
