# Generated by Django 6.0.4 on 2026-04-26 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
